/*
 * -----------------------------------------------------------------------------
 * Created by Ulysses Carlos on 01/02/2026 at 07:24 PM
 *
 * Lecture201.script.js
 * Types of Events and Event Handlers
 * -----------------------------------------------------------------------------
 */

"use strict";

// As before, an event is a signal generated by a DOM node in which something has happened on a
// page.  These events can be handled via Element.addEventListener.  For this example, we'll
// look at the `mouseenter` event:

// const h1 = document.querySelector("h1");
// h1.addEventListener("mouseenter", function(event) {
//     // The mouseenter event is similar to the hover property:
//     window.alert("addEventListener: Great! You are reading the heading. :)");
// });

// You can also attach an event via the Element.onEvent property.
// However, this is considered old school since Element.addEventListener allows us to add multiple functions using the same event.
// h1.onmouseenter = function(event) {
//     // The mouseenter event is similar to the hover property:
//     window.alert("addEventListener: Great! You are reading the heading :)");
// };


const alertH1 = function(event) {
    alert("addEventListener: Great! You're reading the heading :)");
}

h1.addEventListener("mouseenter", alertH1); 
// We can remove an event via Element.removeEventListener, but we have to store the function first:
h1.removeEventListener("mouseenter", alertH1);

// Here's a setTimeout version of the same thing:
setTimeout(() => h1.removeEventListener("mouseenter", alertH1), 3000);

// Finally, there's another way to set an event using an HTML Attribute by defining it directory into the html
// // THIS SHOULDN'T BE USED EVER THOUGH.
// <h1 onclick="alert('Hello World!')"></h1>


